### ISSUE TITLE
rye add --path failed

### ISSUE THREAD

**Issue by indigoviolet** [mitsuhiko/rye#168]
### Steps to Reproduce

```
❯ ls     
4.0 KB a minute ago drwxrwxr-x venky  api_util/
4.0 KB a minute ago drwxrwxr-x venky  do_every/

❯ cd api_util/     

❯ cat ../do_every/pyproject.toml
   1   |[project]
   2   │ name = "do-every"
   3   │ version = "0.1.0"
   4   │ description = "Add a short description here"
   5   │ authors = [
   6   │     { name = "Venky Iyer", email = "indigoviolet@gmail.com" }
   7   │ ]
   8   │ dependencies = [ "loguru~=0.7.0"]
   9   │ readme = "README.md"
  10   │ requires-python = ">= 3.8"
  11   │ 
  12   │ [build-system]
  13   │ requires = ["hatchling"]
  14   │ build-backend = "hatchling.build"
  15   │ 
  16   │ [tool.rye]
  17   │ managed = true

❯ rye add do-every --path ../do_every                                         
Error: failed to resolve package do-every @ file:///${PROJECT_ROOT}/../do_every
Traceback (most recent call last):
  File "<string>", line 20, in <module>
  File "<string>", line 20, in <listcomp>
  File "<string>", line 18, in <genexpr>
  File "/home/venky/.rye/self/lib/python3.10/site-packages/packaging/version.py", line 196, in __init__
    match = self._regex.search(version)
TypeError: expected string or bytes-like object
```

### Expected Result

It's true that I'm not using workspaces, but this is more like sibling libraries using each other than a parent library using support libraries. In any case, I  would have expected this to install the sibling `do-every` library. 

### Actual Result

See above			

### Version Info

❯ rye --version                      
rye 0.1.0
commit: unknown (4c5ef5d59 2023-05-15)
platform: linux (x86_64)
self-python: cpython@3.10

**Comment by CharlesChen0823** [comment]
using `rye add do-every --path ../do_every --absolute` will work.

**Comment by CharlesChen0823** [comment]
from testing, current `rye add --path ./` not work, only `rye add --path ./ --absolute` work. should change the parameter `absolute` to defautl_value `true`? @mitsuhiko

**Comment by mitsuhiko** [comment]
Local references continue to be an issue because it's unclear how they can be handled. It's all very hacky due to lack of actual underlying ecosystem support. I'm not sure what a good course of action is.  The problem with `--absolute` is that it won't work at all for more than a single developer.

**Comment by CharlesChen0823** [comment]
I had trying to resolve without '--absolute' parameters, but currently I have no idea.

**Comment by mitsuhiko** [comment]
This should be resolved now.

**Comment by CharlesChen0823** [comment]
using `hatchling` backend system, generate absolute file path in pyproject.toml, but using `flit_core` and `setuptools`, the path requirements is `"front @ file:///${PROJECT_ROOT}/../front"`, which is not support in `flit_core` and `setuptools`.

**Comment by CharlesChen0823** [comment]
using `hatchling` backend system, generate absolute file path in pyproject.toml, but using `flit_core` and `setuptools`, the path requirements is `"front @ file:///${PROJECT_ROOT}/../front"`, which is not support in `flit_core` and `setuptools`.

**Comment by ischaojie** [comment]
The root of the problem is still `pip-compile`, we should force absolute path when adding local dependencies before `pip-tools` is replaced.

**Comment by mitsuhiko** [comment]
The entire story of local dependencies is a mess sadly because there is no standard for it. :(

**Comment by bluss** [comment]
Not sure if it is known in this discussion but hatch documents relative paths support using `{root:uri}` (but `rye sync` would need to support it as well.)

**Comment by mitsuhiko** [comment]
`rye sync` already supports (in theory) `${PROJECT_ROOT}` but i think it has a bunch of issues.

**Comment by bluss** [comment]
I haven't found any way to use PROJECT_ROOT where rye sync works (without ending up with . (Testing both the ${PROJECT_ROOT}/../foo and  ${PROJECT_ROOT}/foo scenarios). Maybe it looks like the rye side works, but then the pip resolver itself reads out ${PROJECT_ROOT} etc from pyproject.toml (I have no idea.)

**Comment by mitsuhiko** [comment]
Oh indeed it might be that the native read of the `pyproject.toml` is screwing things up.
